// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUBFSPPYHI83O1OH2-Y2dm105VQWws0Bs',
    appId: '1:760448758874:web:92b247c328cd43a7a49463',
    messagingSenderId: '760448758874',
    projectId: 'fitness-app-14835',
    authDomain: 'fitness-app-14835.firebaseapp.com',
    storageBucket: 'fitness-app-14835.appspot.com',
    measurementId: 'G-M0WS097LLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8S6DBU1ht6iRI_0hFN3n18zf2ULqDVRY',
    appId: '1:760448758874:android:514f5a3665b2f3c0a49463',
    messagingSenderId: '760448758874',
    projectId: 'fitness-app-14835',
    storageBucket: 'fitness-app-14835.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdh-zegujx2IUO_iIUW99EYD48pKdv_-o',
    appId: '1:760448758874:ios:c4b1f8282ab88430a49463',
    messagingSenderId: '760448758874',
    projectId: 'fitness-app-14835',
    storageBucket: 'fitness-app-14835.appspot.com',
    iosBundleId: 'com.example.flutterFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdh-zegujx2IUO_iIUW99EYD48pKdv_-o',
    appId: '1:760448758874:ios:bc2bc513020304bfa49463',
    messagingSenderId: '760448758874',
    projectId: 'fitness-app-14835',
    storageBucket: 'fitness-app-14835.appspot.com',
    iosBundleId: 'com.example.flutterFitnessApp.RunnerTests',
  );
}
